import Foundation

struct Quote {
    let text: String
    let author: String
}

let quotes: [Quote] = [
    Quote(text: "The only way to do great work is to love what you do.", author: "Steve Jobs"),
    Quote(text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
    Quote(text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill"),
    Quote(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
    Quote(text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
    Quote(text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair"),
    Quote(text: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", author: "Roy T. Bennett"),
    Quote(text: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela"),
    Quote(text: "The only impossible journey is the one you never begin.", author: "Tony Robbins"),
    Quote(text: "Your limitation—it's only your imagination.", author: "Unknown"),
    Quote(text: "Push yourself, because no one else is going to do it for you.", author: "Unknown"),
    Quote(text: "Great things never come from comfort zones.", author: "Unknown"),
    Quote(text: "Dream it. Wish it. Do it.", author: "Unknown"),
    Quote(text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown"),
    Quote(text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown"),
    Quote(text: "Dream bigger. Do bigger.", author: "Unknown"),
    Quote(text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown"),
    Quote(text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown"),
    Quote(text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery"),
    Quote(text: "Little things make big days.", author: "Unknown"),
    Quote(text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown"),
    Quote(text: "Don't wait for opportunity. Create it.", author: "Unknown"),
    Quote(text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown"),
    Quote(text: "The key to success is to focus on goals, not obstacles.", author: "Unknown"),
    Quote(text: "Dream it. Believe it. Build it.", author: "Unknown"),
    Quote(text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson"),
    Quote(text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis"),
    Quote(text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson"),
    Quote(text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe"),
    Quote(text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson"),
    Quote(text: "The secret of getting ahead is getting started.", author: "Mark Twain"),
    Quote(text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi"),
    Quote(text: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine"),
    Quote(text: "If you can dream it, you can do it.", author: "Walt Disney"),
    Quote(text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"),
    Quote(text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn"),
    Quote(text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller"),
    Quote(text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson"),
    Quote(text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill"),
    Quote(text: "Someone is sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett"),
    Quote(text: "Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them.", author: "Vaibhav Shah"),
    Quote(text: "Opportunities don't happen. You create them.", author: "Chris Grosser"),
    Quote(text: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein"),
    Quote(text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey"),
    Quote(text: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso"),
    Quote(text: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus"),
    Quote(text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou"),
    Quote(text: "Either you run the day, or the day runs you.", author: "Jim Rohn"),
    Quote(text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford"),
    Quote(text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"),
    Quote(text: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe"),
    Quote(text: "The best revenge is massive success.", author: "Frank Sinatra"),
    Quote(text: "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", author: "Zig Ziglar"),
    Quote(text: "Life shrinks or expands in proportion to one's courage.", author: "Anais Nin"),
    Quote(text: "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", author: "Vincent Van Gogh"),
    Quote(text: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle"),
    Quote(text: "The only person you should try to be better than is the person you were yesterday.", author: "Anonymous"),
    Quote(text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein"),
    Quote(text: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb"),
    Quote(text: "There are no traffic jams along the extra mile.", author: "Roger Staubach"),
    
    Quote(text: "Always choose harder right over easy wrong and never let your wish bone grow where a backbone should be.", author: "Unknown"),
    Quote(text: "Life is like a war. You either enter the battlefield fully armed or surrender as soon as you enter. Make a choice.", author: "Unknown"),
    Quote(text: "Network builds NET-WORTH", author: "Unknown"),
    Quote(text: "\"An extraordinary process whereby you become the person you always should have been\" is a quote by David Bowie about the concept of aging.", author: "David Bowie"),
    Quote(text: "Benjamin Franklin's primary \"certainty\" or memorable statement is the idea that \"nothing is certain except death and taxes.\"", author: "Benjamin Franklin"),
    Quote(text: "YOU SWEAT IN PRACTICE SO YOU DO NOT BLEED IN WAR", author: "Unknown"),
    Quote(text: "\"Never give a sword to a man who can't dance\" is a quote attributed to Confucius, and it serves as a metaphor warning against giving power, responsibility, or a dangerous tool to someone who lacks the necessary skill, grace, or wisdom to handle it responsibly.", author: "Confucius"),
    Quote(text: "Every single fear is linked to the fear of death, death of the ego or death of the physical body. And since every fear is linked to the fear of death it is actually fear of time. Which is just the fear of unlived life. SO LIVE MORE & LIVE MORE INTENSELY.", author: "Unknown"),
    Quote(text: "Being alone is a power, very few can handle it.", author: "Unknown"),
    Quote(text: "The truth will set you free. But not until it is finished with you.", author: "Unknown"),
    Quote(text: "You can’t call yourself peaceful unless you’re capable of great violence, if you’re not capable of violence you are not peaceful you’re harmless.", author: "Unknown"),
    Quote(text: "\"The pen isn't mightier than the sword. Pens do not win battles, nor swords write poetry. Mighty is the hand that knows when to pick up the pen or pick up the sword.\" - Wiegraf Folles", author: "Wiegraf Folles"),
    Quote(text: "Some of us never found time to be happy because we were too busy trying to be strong.", author: "Unknown"),
    Quote(text: "Pain is inevitable, suffering is optional.", author: "Unknown"),
    Quote(text: "You think you can traumatise an international student, We left the world back home knowing that we will never get the same home back again. We can go out eat, go to movies/concerts alone. We vibe with the people who say horrible things and we can still make them believe we don't understand anything. We learn new cultures and languages. All with a big smile.", author: "Unknown"),
    Quote(text: "\"Sometimes you think that you want to disappear but all you really want is to be found.\"", author: "Unknown"),
    Quote(text: "IF YOU HAVE THE POWER TO GO ALONE TO A RESTAURANT OR A MOVIE THEATRE THEN YOU CAN DO ANYTHING IN YOUR LIFE.", author: "Unknown"),
    Quote(text: "The magic you are looking for is in the work you’re avoiding.", author: "Unknown"),
    Quote(text: "Peniaphobia - fear of poverty.", author: "Unknown"),
    Quote(text: "Koinophobia - fear of living an ordinary life.", author: "Unknown"),
    Quote(text: "I’m an entrepreneur, I live for disruption.", author: "Unknown"),
    Quote(text: "Look back at your childhood by using your childhood pics.", author: "Unknown"),
    Quote(text: "Why do you keep imagining buying good eyes, why do you keep imagining driving a really nice car & other great things in life. That’s because God is talking to you. He’s showing you something that he has for you.", author: "Unknown"),
    Quote(text: "If you don't heal what hurt you, you'll bleed on people who didn't cut you.", author: "Unknown"),
    Quote(text: "When you build in silence, people don’t know what to attack.", author: "Unknown"),
    Quote(text: "Money does buy happiness, you just gotta give it away.", author: "Unknown"),
    Quote(text: "Please don’t waste your time explaining houseflies why honey is better than shit.", author: "Unknown"),
    Quote(text: "Sometimes you close a client and he or she just doesn’t know it yet.", author: "Unknown"),
    Quote(text: "THEY HATE US CAUSE THEY AIN'T US.", author: "Unknown"),
    Quote(text: "The real big boys own millions of dollars worth of private jets not just a $300,000 car.", author: "Unknown"),
    Quote(text: "Top 1% consider having to do many things but not enough time to do all as a good problem and indication of the working in the right direction.", author: "Unknown"),
    Quote(text: "\"Witches call it spells. Religious people call it prayer. Spiritualists call it manifestation. Atheists call it the placebo effect. Scientists call it quantum physics. Everyone's arguing over its name, but no one is denying its existence.\"", author: "Unknown"),
    Quote(text: "If you go into a party and you’re not the fittest person there, make sure when you meet anyone from that party, your account & brain is fatter, and you’re fitter.", author: "Unknown"),
    Quote(text: "A non-reader is same as an illiterate when it comes to intellect.", author: "Unknown"),
    Quote(text: "I want to be so private that if you know my business, I’ll know who blabbered.", author: "Unknown"),
    Quote(text: "My age is pretty weird, some are getting married, some are getting pregnant and me…. still asking permission to go out.", author: "Unknown"),
    Quote(text: "If you keep on spending on things you don’t need, you’ll end up with debt you don’t want.", author: "Unknown"),
    Quote(text: "Imagine a movie where the main character lays in the bed and does nothing, BORING RIGHT (NOW LOOK AT YOU)", author: "Unknown"),
    Quote(text: "It is called the 1% for a reason. 99% of people cannot handle the discipline.", author: "Unknown"),
    Quote(text: "Most people aren’t obsessed with their goals because they don’t believe they’re worthy of them. It is easy to dream about what you want but in between where you are and what you want, there’s a tremendous amount of stuff you got to change and do.", author: "Unknown"),
    Quote(text: "Imagine telling your kids that you quit because it was hard….. STAY DISCIPLINED.", author: "Unknown"),
    Quote(text: "Do not worry dad, your boy is going to make it one day, I am a guy with ambition and make you proud one day like you used to say think you can and you can. We will make it out.", author: "Unknown"),
    Quote(text: "A man who controls his stomach, penis and tongue has solved 99% of his problems.", author: "Unknown"),
    Quote(text: "Who says money does not buy happiness, you just have to give it away.", author: "Unknown"),
    Quote(text: "According to Mensa which is a known platform and service and is utterly famous with their relation to IQ and everything there is to about IQs said in one of their articles that men with more chest hair are more intelligent, in some way higher amount of chest hair is directly proportional to higher intelligence.", author: "Unknown"),
    Quote(text: "\"The blood of the covenant is thicker than the water of the womb.\" - The saying means that chosen bonds are more significant than the bonds with family or “water of the womb.” More directly, it means that relationships you make yourself are far more important than the ones that you don't choose.", author: "Unknown"),
    Quote(text: "Never negotiate with your inner bitch, because if you do so you choose easy over difficult, and this will kill the beast within you and let the inner bitch win.", author: "Unknown"),
    Quote(text: "People make fun of the guy who stays home every night and does nothing but in reality he is a genius.", author: "Unknown"),
    Quote(text: "Keep trading until your 1% stop loss can buy a Ferrari.", author: "Unknown"),
    Quote(text: "Trading is 90% waiting and 10% execution.", author: "Unknown"),
    Quote(text: "No trading day is better than a losing day.", author: "Unknown"),
    Quote(text: "Professional traders don’t predict - they react.", author: "Unknown"),
    Quote(text: "There are people still scrolling & chasing girls, Be the 1%.", author: "Unknown"),
    Quote(text: "It is hard to stop trading once you get a taste of profits.", author: "Unknown")

]
